services:
  - type: web
    name: FakeNewsDetection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: "10000"   
    autoDeploy: true
